### ISSUE TITLE
SpringBoot: Error when re-enabling plugin after being disabled: AnnotationConfigApplicationContext - exception

### ISSUE THREAD

**Issue by laurentkvb** [pf4j/pf4j-spring#13]
In combination with the PF4J-update project, I am using pf4j spring for Spring Boot. 

I am trying to create a REST-API for plugin management in Spring Boot, where plugins can be installed, uninstalled, enabled and disabled at runtime.

I have been able to successfully load a plugin & start from the repository at runtime. For these calls, I have been using `pluginManager.disablePlugin("hello-plugin")` & `pluginManager.enablePlugin("hello-plugin")`. 

Before the `enablePlugin` & after executing `disablePlugin` of the "hello-plugin" I am able to call the 
`PluginManager.getExtensionClasses(Greeting.class)` there's is no problem.

Then I try to re-enable the plugin again with the enablePlugin("hello-plugin") method. It all works, however when I want to access the "hello-plugin" with the pluginmanager.getExtensionClasses() I get the following error:

```
java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@6df20ade has been closed already
```

With this object    `PluginState state = pluginManager.startPlugin(mPluginId)`
I can see that my "hello-plugin" has started, but I am not able to access it via the getExtension methods from the pluginManager. 

This is my SpringConfiguration:
```java
@Bean
public SpringPluginManager pluginManager() {
    return new SpringPluginManager() {
        @Override
        protected PluginClasspath createPluginClasspath() {
            return isDevelopment() ? new GradleDevelopmentPluginClasspath() : new DefaultPluginClasspath();
        }
    };
}

@Bean
@DependsOn("pluginManager")
public UpdateManager updateManager() {
    return new UpdateManager(mPluginManager);
}
```

Currently, what works for me to "enable" a plugin after disabling the plugin is to uninstall the plugin and then re-install the plugin. But that maybe not be the best option as you may want to save the current state of the plugin.

**Comment by decebals** [comment]
> I have been able to successfully load a plugin & start from the repository at runtime. For these calls, I have been using pluginManager.disablePlugin("hello-plugin") & pluginManager.enablePlugin("hello-plugin").

I don't understand why you call `disablePlugin` and `enablePlugin` to load a plugin & start from repository at runtime. Why you don't use [UpdateManager.installPlugin](https://github.com/pf4j/pf4j-update/blob/master/src/main/java/org/pf4j/update/UpdateManager.java#L231) method?
If you want to load a plugin from your file system you can use [PluginManager.loadPlugin](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginManager.java#L74) method. 

Related to the exception, the only one place where the ApplicationContext is closed is when you stop a [SpringPlugin](https://github.com/pf4j/pf4j-spring/blob/master/pf4j-spring/src/main/java/org/pf4j/spring/SpringPlugin.java#L46).
