### ISSUE TITLE
Under certain circumstances, SpringPluginManager does not identify loaded plugins

### ISSUE THREAD

**Issue by sfines** [pf4j/pf4j-spring#14]
```AbstractEventManager.whichPlugin()``` attempts to determine which plugin owns an extension class by comparing their classloaders. Under certain curcumstances (Such as running in IntelliJ) the classloader used will not contain the package but the parent classloader will. 

I Overrode the whichPlugin() method in SpringPluginManager and the problem is resolved: 
```java
import org.pf4j.PluginWrapper;
import org.pf4j.spring.SpringPluginManager;

public class SpringPluginManagerExt extends SpringPluginManager {
    @Override
    public PluginWrapper whichPlugin(Class<?> clazz) {
        ClassLoader classLoader = clazz.getClassLoader();
        for (PluginWrapper plugin : getResolvedPlugins()) {
            if (plugin.getPluginClassLoader() == classLoader || plugin.getPluginClassLoader().getParent() == classLoader) {
                return plugin;
            }
        }

        return null;
    }
}
```

This method is probably not ideal... the PluginClassloader should properly fill out the packages map and then use that or some other mechanism to determine ownership...

**Comment by decebals** [comment]
Sorry for late response. I understand what you say and I think that makes sense. 
I am not sure if `plugin.getPluginClassLoader().getParent() == classLoader` is reliable.
The parent of `PluginClassLoader` is the application class loader.
I don't know how other people use `PluginManager.whichPlugin` but I pass as parameter only some classes that make sense (extensions, extension points, ...), classes that exist in the plugin jar/zip.

Can you give me a concrete example (from your application) of `whichPlugin` call when the actual implementation (without || `plugin.getPluginClassLoader().getParent() == classLoader`) failed.

**Comment by decebals** [comment]
@sfines 
I don't know what to do with this issue.

> Can you give me a concrete example (from your application) of whichPlugin call when the actual implementation (without || plugin.getPluginClassLoader().getParent() == classLoader) failed?

Do you have a response for above question?

> the PluginClassloader should properly fill out the packages map and then use that or some other mechanism to determine ownership...

It's a solution. My idea is to keep `PluginClassLoader` as simple as possible, to be able to come with any ClassLoader implementation. We will see.

**Comment by decebals** [comment]
I will close this issue. I added a new [section](https://pf4j.org/doc/class-loading.html) in documentation to explain in detail how classes are loaded in PF4J.
