### ISSUE TITLE
How to scpecify the plugins location using Spring Boot?

### ISSUE THREAD

**Issue by hudrogen** [pf4j/pf4j-spring#15]
I'm trying to load plugins to base Spring Boot application. But I cannot figure out how to specify the location of plugins. Becouse SpringPluginManager doesn't have constructor with Path argument like DefaultPluginManager.
Here is link to my project repository https://github.com/hudrogen/parent-spring-pf4j
It is based on the demo project.

**Comment by decebals** [comment]
Yes, it's useful to add a new constructor with parameter in `SpringPluginManager`, similar with `DefaultPluginManager`. If you have time, please submit a PR (pull request) with this modification.
In the mean time, to pass the plugins location you can use the system property `pf4j.pluginsDir` with your desire value (default is "plugins") via:
- command line `-Dpf4j.pluginsDir=plugins`
- code `System.setProperty("pf4j.pluginsDir", "plugins")`

**Comment by decebals** [comment]
By the way, I discovered some time ago this project https://github.com/vindell/spring-boot-starter-pf4j2, maybe is useful.
