### ISSUE TITLE
Spring JPA Repository integration|| issue while inserting data through hibernate , Spring JPA Repository

### ISSUE THREAD

**Issue by Prashanttorat** [pf4j/pf4j-spring#18]
i am able to integrate spring plugin with my main application context as parent child, controller and service and repository annotations also discovered, when i select from any table that i can see select query log in logger

 But when i do operation like insert then it is not saving data to table also query is not printed in logger.

**Comment by decebals** [comment]
You say that select operation works as expected (you see the sql in log) and the insert operation doesn't work?

**Comment by Prashanttorat** [comment]
yes , select is working and insert not working, i have set hibernate show sql flag as true and select statements are getting logged where as insert not , and there is no any exception

**Comment by decebals** [comment]
It's strange. I don't see how PF4J can lead to a such behavior. You can put PF4J log on debug (or trace) level to have more information but again.

**Comment by Prashanttorat** [comment]
i have tried like created data source in plugin and not sharing application of main then it is working 

but i wanted to share application context like parent - child , use only one data source which is created by parent application context

let me explain what i am trying to achieve is there will be parent app context which is main will create child context for plugins for the same i have written code like this

AnnotationConfigServletWebServerApplicationContext appContext = (AnnotationConfigServletWebServerApplicationContext) pluginManager.getApplicationContext();

    	  AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext();

    	  applicationContext.setClassLoader(getWrapper().getPluginClassLoader());
    	  applicationContext.setParent(appContext);


i have created data source in parent context only and in plugin i am just using parent context has data sourec, in spring jpa config injected data source  and created entity manger factory for plugin

one thing here is data source created by root application class loader and child entities and entity manager factory is created bu Plugin class loader - may be this causing something

do you have any thing on this?

**Comment by decebals** [comment]
Did you tried to search in closed issues, to see if you find a solution?
- https://github.com/pf4j/pf4j/issues/49
- https://github.com/pf4j/pf4j-spring/issues/17

**Comment by Prashanttorat** [comment]
Yes, i have gone through these issue , so i came to know about context sharing and parent child relation context.

Spring beans are also resolved using annotation itself service is created, spring JPA repository object is also created

if i set hbm2ddl.auto propert as create the its also creating table for the same entity which is part of plugin

only on  save - there is nothing happen, no log no exception

**Comment by decebals** [comment]
And https://github.com/pf4j/pf4j-spring/issues/7?

**Comment by Prashanttorat** [comment]
**i am able to discovered controller and services that is not issue**.

issue is in while saving data using hibernate , in my plugin has Spring JPARepositry (org.springframework.data.jpa.repository.JpaRepository) used  to deal with db operaition 

**only thing is data source is created at parent context and same data source using in child context which is plugin**

**Comment by decebals** [comment]
@Prashanttorat 
I don't know how can I help you. I don't use Spring in my applications. You have a lot of information about how pf4j and pf4j-spring work. pf4j-spring is a very light project and you can dive in sources very easy.
Maybe other people that use Spring can help you.

**Comment by Prashanttorat** [comment]
Hi Decebal Suiu, Thanks for help, issue resolved, i was trying use same entity manger and transaction manager which is created by parent context, which is actually false, Scope is different of parent main context and plugin context

i have just created Entity manager Factory and transaction in plugin context now it is working perfectly as expected
