### ISSUE TITLE
Third party Dependency in Plugin

### ISSUE THREAD

**Issue by Prashanttorat** [pf4j/pf4j-spring#19]
i am not aware of how to add dependency in plugin!

i am facing issue while adding third party jar "apache poi" in plugin, i have added maven dependency in pom file, i am able to build plugin jar file but getting ClassnotFound exception at run time

**Comment by decebals** [comment]
Can you add more detail please? Can you share with us the plugin's pom.xml? Maybe you create a thin jar and not a fat jar. Please take a look at your plugin's jar and see if the find the POI's classes.

**Comment by decebals** [comment]
@Prashanttorat 
Did you solved the problem?

**Comment by decebals** [comment]
I suppose that the problem is solved in the meantime so I will close the issue. If you consider that you need more information, please open it.

**Comment by MohankumarD** [comment]
Hi Decebals,
I am facing the same issue, can you please help on this how to add a dependency for third-party jar..
