### ISSUE TITLE
JPA Entity Scanning won't pick up entities from plugins

### ISSUE THREAD

**Issue by dtrunk90** [pf4j/pf4j-spring#27]
It's not possible to define JPA entities in a plugin.

Here's the plugins entity: https://github.com/keering/keering/blob/master/plugins/widgets/chat/src/main/java/com/github/keering/plugins/widgets/chat/model/jpa/ChatHistory.java
And this is how I set entity scanning: https://github.com/keering/keering/blob/master/app/src/main/java/com/github/keering/app/configuration/PluginConfiguration.java#L29-L40

Debug log is only picking up these classes:
```
2019-01-03 12:07:19.740 DEBUG 13507 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : PersistenceUnitInfo [
        name: default
        persistence provider classname: null
        classloader: org.springframework.boot.loader.LaunchedURLClassLoader@5f341870
        excludeUnlistedClasses: true
        JTA datasource: null
        Non JTA datasource: HikariDataSource (HikariPool-1)
        Transaction type: RESOURCE_LOCAL
        PU root URL: file:/home/danny/workspace/keering/build/app-1.0-SNAPSHOT.jar
        Shared Cache Mode: UNSPECIFIED
        Validation Mode: AUTO
        Jar files URLs []
        Managed classes names [
                com.github.keering.app.model.jpa.UserConfiguration$UserConfigurationId
                com.github.keering.app.model.jpa.UserConfiguration
                com.github.keering.api.model.jpa.User
                com.github.keering.api.model.jpa.Role]
        Mapping files names []
        Properties []
```

I guess it's due to different class loaders for main app and plugins.

You can start the project by running: `$ ./gradlew build && cd build && java -jar app-1.0-SNAPSHOT.jar`

**Comment by decebals** [comment]
Maybe https://github.com/pf4j/pf4j-spring/issues/18 can help.

**Comment by dtrunk90** [comment]
I don't understand what he is talking about exactly. It's not detailed enough. I guess I have to write this code in my `AbstractPlugin` class constructor?! But there's no reference to the main app context. He is just creating a new context instance which spring boot already does in my `Application` class.

**Comment by dtrunk90** [comment]
I did the following changes now but without success:
```java
public abstract class AbstractPlugin extends SpringPlugin {
	public AbstractPlugin(PluginWrapper wrapper) {
		super(wrapper);
	}

	@Override
	protected ApplicationContext createApplicationContext() {
		ApplicationContext appContext = ((SpringPluginManager) getWrapper().getPluginManager()).getApplicationContext();
		AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext();
		applicationContext.setClassLoader(getWrapper().getPluginClassLoader());
		applicationContext.setParent(appContext);
		applicationContext.refresh();
		return applicationContext;
	}
}
```

**Comment by decebals** [comment]
Maybe @Prashanttorat can explain you better, because he succeeded.
The short story is tha each Spring plugin is loaded by a different ClassLoader and it has a different ApplicationContext. So you have a parent ApplicationContext (the context of your application) and multiple child AppliicationContext (one context for each plugin). So you have a ApplicationContext hierarchy [1]. Child contexts can resolve beans from their parent – but never vice versa, and sibling contexts are isolated from one another  - and this isolation is a problem in your application. 

[1] https://stackoverflow.com/questions/5132604/why-use-spring-applicationcontext-hierarchies

**Comment by dtrunk90** [comment]
Thanks, I took a quiet minute and now it is working.

First you have to override `SpringPlugin.createApplicationContext` in order to set the application context from main application as parent and register a `@Configuration` annotated class which creates the entity manager factory bean and transaction manager bean:

```java
public abstract class AbstractPlugin extends SpringPlugin {
	public AbstractPlugin(PluginWrapper wrapper) {
		super(wrapper);
	}

	@Override
	protected ApplicationContext createApplicationContext() {
		ApplicationContext appContext = ((SpringPluginManager) getWrapper().getPluginManager()).getApplicationContext();
		AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext();
		applicationContext.setClassLoader(getWrapper().getPluginClassLoader());
		applicationContext.setParent(appContext);
		applicationContext.register(JpaConfiguration.class);
		applicationContext.refresh();
		return applicationContext;
	}
}

@Configuration
public class JpaConfiguration {
	@Autowired
	private EntityManagerFactoryBuilder entityManagerFactoryBuilder;

	@Autowired
	private DataSource dataSource;

	@Bean
	public AbstractEntityManagerFactoryBean entityManagerFactoryBean() {
		return entityManagerFactoryBuilder.dataSource(dataSource).packages("com.github.keering.*.model.jpa", "com.github.keering.plugins.widgets.chat.model.jpa").build();
	}

	@Bean
	public PlatformTransactionManager transactionManager() {
		return new JpaTransactionManager();
	}
}
```

This way the main application context's entity manager can access its entities and the plugin application context's entity manager can access the main application context entities and its own entities.

**Comment by AaricChen** [comment]
Hi @dtrunk90 

after add **EntityManagerFactoryBean**

I still got 
```
java.lang.IllegalArgumentException: Not a managed type
```
the **Repository** can found in my plugin, but entity class is not recognized.
please help on this.
thanks in advance.

**Comment by dtrunk90** [comment]
Hi @AaricChen 
I completely moved to Spring Factories. Can't help here, sorry.

**Comment by hasanli-orkhan** [comment]
I have the same problem.  Not a managed type: class ***
Has anyone managed to solve this problem?

**Comment by decebals** [comment]
Can someone post on GitHub a very simple project that replicates the problem? It will be more easy for us to have a concrete start point/

**Comment by hasanli-orkhan** [comment]
> Can someone post on GitHub a very simple project that replicates the problem? It will be more easy for us to have a concrete start point/

Hi! Here is the simple project with integrated H2 database.
https://github.com/hasanli-orkhan/pf4j-spring-data-test

Spring version - 3.1.6
pf4j-spring version - 0.8.0

Here is the exception on start:
`Caused by: java.lang.IllegalArgumentException: Not a managed type: class com.example.plugin.model.Test`


Thanks in advance!
