### ISSUE TITLE
Not compatible with pf4j-update & pf4j-spring

### ISSUE THREAD

**Issue by syifarahmat** [pf4j/pf4j-spring#31]
Not compatible with pf4j-update, because different basics libraries (pf4j-spring uses **pf4j: 2.5.0** but pf4j-update uses **pf4j: 3.0.1**) as a result when run error: Caused by: java.lang.ClassNotFoundException: org.pf4j .PluginRuntimeException

**Comment by otmanel31** [comment]
Is there any update on this issue, as i will need the update feature in spring context ?

**Comment by decebals** [comment]
I will make pf4j-spring compatible with pf4j 3.0.1 as soon as possible.

**Comment by decebals** [comment]
I updated pf4j-spring to use pf4j 3.0.1.
I published the SNAPSHOT version (0.6.0-SNAPSHOT) of pf4j-spring. Please try the SNAPSHOT version. If everything is OK I will release a new version.
For how to add the SNAPSHOT repo to your project see https://pf4j.org/dev/maven.html.

**Comment by syifarahmat** [comment]
Thank's
