### ISSUE TITLE
Communication between plugins

### ISSUE THREAD

**Issue by otmanel31** [pf4j/pf4j-spring#32]
Hi decebals,

I'm trying to enable communication between two plugins. For example, i would like, when there is an incomming message on my plugin 1 to notify plugin2 and finally plugin2 to give a response to plugin1. 
When i would like send  a message to plugin2, i was stuck as i don't know or i haven't any known method of plugin2 in my plugin1. 

So, may be i've to extend the plugin class to create my custom plugin and extends it on all plugin i need to enable communication by implementing two methods:
- notifyIncomingEvent()
- sendResponse()

This is what i try to achieve:
```java
public class Main extends Plugin implements MainManager {

    private static final Logger LOGGER = LoggerFactory.getLogger(Core.class);

    private SpringPluginManager pm;
    private String message;
    List<PluginWrapper> plugins;

    public Main(PluginWrapper wrapper) {
	    super(wrapper);

	    LOGGER.info("Core instanciation");
	    message = "Incoming message";
	    pm = (SpringPluginManager) wrapper.getPluginManager();
	    
    }

    @Override
    public void start() throws PluginException {
	    super.start();

	    LOGGER.info("Core succesfully started");
	    plugins =  pm.getPlugins();
	    //plugins.forEach(p->LOGGER.info("some id " + p.getPluginId()));
	    fromOut(message);
    }

    public void fromOut(String message) {
	    LOGGER.info("incoming message => " + message);
	    /*send data to in plugin*/
	    
	    plugins.forEach(p -> {
		    if (p.getPluginId().equals("in-plugin")) {
			    // HERE NOTIFY PLUGIN2
                p.notifyIncomingEvent(message);
		    }
	    });
    }

}
```

For you is it the good way ?

**Comment by otmanel31** [comment]
I tried something like getWapper().getPluginManager in my constructor plugin. Then i tried to get for example extensions list and when i count it, i have 0 found. When i execute it  in my main app, it found my extensions.

**Comment by decebals** [comment]
Take a look at:
- https://github.com/pf4j/pf4j/issues/79
- https://groups.google.com/forum/#!topic/pf4j/osvqpNVqkgY

**Comment by otmanel31** [comment]
Thanks, the #79 issue is a pull approach ? 
using getwrapper.getPluginmanager() is  a pull approach  isn't it ? 
I'm able to list my plugins other plugin inside a specific plugin.
I tried something else .... I created a custom plugin (which is abstract) in my api (where are interfaces and abstract class) .... then i'm able in the main app to check the className of plugin and cast it to given Abstract class of my api and call specific method of my plugins. For example plugin1.setContextForYou() or plugin1.setListForSpecificTypeOfPlugins() ..... i think this is a push approach ?

**Comment by otmanel31** [comment]
As describe in previous comment, communication between plugin is done. For me , there are two ways :
- push approach
- pull approach
