### ISSUE TITLE
Questions: custom plugin or extension use

### ISSUE THREAD

**Issue by otmanel31** [pf4j/pf4j-spring#33]
Hi Decebals,

I've questions about plugins and extensions. As describe in documentations, a plugin enable some feature for managins plugins. So, i extend plugin (in api), implement it on each jar and enable custom method that could be called by app or other plugin later (using custom Type/interface declared in api). But there are extensions and as describe in documentation, an extension is a specific behaviour of an application (or for a plugin). I think custom method that are created in my plugin could be an extension ... for me twice are possible but i didn't see pro and con of two scenario ... And i don't know if it's a good idea to add custom method or specific behaviour (like external request for example) in the plugin instead of using extensions

**Comment by decebals** [comment]
Sky's the limit when you use PF4J. PF4J is very flexible and powerful. Try to ignore PF4J in first step and think your business like a monolithic application. The use of PF4J comes natural after this.
For example, use an event driven approach, declare an interface `MyMessageListener` with one method like `onMessage(String/Message message)`. If you want to be notified, implement this interface.
Make this interface an extension point (`extends ExtensionPoint`). In your message provider (a plugin probably or directly your application) when a new message arrives, use `pluginManager.getExtensions(MyMessageListener)` to get all listeners and for each listener call `onMessage`. That is all. It's easy and natural. 
For a real life scenario/usage see https://github.com/ta4j/ta4j/issues/411#issuecomment-510634048.

**Comment by otmanel31** [comment]
Thanks for quite reply Decebals .... I will try it ... currently i haven't got any extensions in my app, only custom pluginManager and differents customs plugins that extends Pf4j DefaultPlugin and could implements some interfaces .... i will see then if i should migrate custom method into extensions ....  Thanks for your advice.
