### ISSUE TITLE
Can't get working the functionality "Disable Plugin"

### ISSUE THREAD

**Issue by carlosFlux** [pf4j/pf4j-spring#41]
From AbstractPluginManager.loadPlugins() its called AbstractPluginManager.loadPluginFromPath() that recognise and marks plugins as DISABLED (I'm only adding the disabled.txt in the plugins folder). But later AbstractPluginManager.resolvePlugins() mark the same plugin as RESOLVED. Is there something I'm missing?

**Comment by decebals** [comment]
@carlosFlux 
Which PF4J version do you use?

**Comment by carlosFlux** [comment]
Hello, These are the versions that I'm using

[INFO] \- org.pf4j:pf4j-spring:jar:0.5.0:compile
[INFO]    +- org.pf4j:pf4j:jar:2.3.0:compile
[INFO]    |  +- org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO]    |  \- com.github.zafarkhaja:java-semver:jar:0.9.0:compile
[INFO]    +- org.springframework:spring-core:jar:4.0.5.RELEASE:compile
[INFO]    |  \- commons-logging:commons-logging:jar:1.1.3:compile
[INFO]    +- org.springframework:spring-context:jar:4.0.5.RELEASE:compile
[INFO]    |  +- org.springframework:spring-aop:jar:4.0.5.RELEASE:compile
[INFO]    |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO]    |  +- org.springframework:spring-beans:jar:4.0.5.RELEASE:compile
[INFO]    |  \- org.springframework:spring-expression:jar:4.0.5.RELEASE:compile
[INFO]    +- log4j:log4j:jar:1.2.16:compile
[INFO]    +- org.slf4j:slf4j-log4j12:jar:1.7.5:compile
[INFO]    \- commons-lang:commons-lang:jar:2.4:compile

Thanks.

**Comment by carlosFlux** [comment]
Oh it's solved in a recent version of the core library. Thanks for your time.
