### ISSUE TITLE
Dependencies of system extension inside SpringPluginManager's host not autowired

### ISSUE THREAD

**Issue by lhanda** [pf4j/pf4j-spring#42]
Have a problem when using SpringPluginManager in a SpringBoot project with a system extension defined. Inside the system extension I have annotated a dependency using the Spring '@Autowired' annotation like how you would define for a SpringPlugin's plugin extension. However, upon running the code, the dependency inside the system extension was not injected because the SpringExtensionFactory's create method only does so for SpringPlugin's plugin extension only.

Below is the extract of the SpringExtensionFactory create method and my suggested modifications
  ```
 @Override
    public <T> T create(Class<T> extensionClass) {
        T extension = createWithoutSpring(extensionClass);
        if (autowire && extension != null) {
            // test for SpringBean
            PluginWrapper pluginWrapper = pluginManager.whichPlugin(extensionClass);
            if (pluginWrapper != null) { // is plugin extension
                Plugin plugin = pluginWrapper.getPlugin();
                if (plugin instanceof SpringPlugin) {
                    // autowire
                    ApplicationContext pluginContext = ((SpringPlugin) plugin).getApplicationContext();
                    pluginContext.getAutowireCapableBeanFactory().autowireBean(extension);
                }
            } else if (this.pluginManager instanced SpringPluginManager) { // is system extension and plugin manager is SpringPluginManager
                SpringPluginManager springPluginManager = (SpringPluginManager) this.pluginManager;
                ApplicationContext pluginContext = springPluginManager.getAppplicationContext();
                pluginContext.getAutowireCapableBeanFactory().autowireBean(extension);
            }
        }

        return extension;
    }
```

**Comment by decebals** [comment]
@lhanda 
I understand your problem, thanks for reporting it.

> Below is the extract of the SpringExtensionFactory create method and my suggested modifications

Can you create a PR please? Did you tested your suggestion on your code?

**Comment by lhanda** [comment]
> @lhanda
> I understand your problem, thanks for reporting it.
> 
> > Below is the extract of the SpringExtensionFactory create method and my suggested modifications
> 
> Can you create a PR please? Did you tested your suggestion on your code?

Yes, I tested locally. Put up a PR as per requested, please review, tks.

**Comment by decebals** [comment]
> Yes, I tested locally. Put up a PR as per requested, please review, tks.

I merged your PR. Thanks for your contribution!
Please close this issue.

**Comment by lhanda** [comment]
You are welcome.
