### ISSUE TITLE
Next release version

### ISSUE THREAD

**Issue by sharat87** [pf4j/pf4j-spring#45]
Apologies if this is not the right avenue for this question.

The current release of `pf4j-spring` available on Maven central is version 0.5.0 which depends on pf4j version 2.x. I see that the latest HEAD uses 3.0.1. May I know when a new release will be pushed so we can start using it please?

Ideally we'd like to upgrade to using pf4j 3.2.0 (which is the latest as of today), but even 3.0.1 would be nice.

If there's anything blocking that needs to be fixed before a release, please let me know. We'll help if it's something we can take up.

Thanks for all your work.

**Comment by decebals** [comment]
@sharat87 

Your question is good.
The code is already prepared for PF4J 3.x:
![image](https://user-images.githubusercontent.com/1248311/78557398-64454c00-7819-11ea-8d12-684f402b027b.png)

I will try to create a new release today or tomorrow. Please try to use the SNAPSHOT version until release.

**Comment by sharat87** [comment]
Thank you very much. If you plan to do it within this week, then I'd rather wait for the actual release. 🍰

**Comment by decebals** [comment]
A new version (0.6.0) is already available. The new version uses the latest version of PF4J (3.2.0).

**Comment by sharat87** [comment]
Awesome, got it. Thanks for the quick turnaround man!
