### ISSUE TITLE
SpringPlugin start/stop/start results in Exception

### ISSUE THREAD

**Issue by michael-becker** [pf4j/pf4j-spring#58]
I tested the following calls:

```java
pluginManager.startPlugin(PLUGIN_ID);
pluginManager.getExtensions(PLUGIN_ID);
pluginManager.stopPlugin(PLUGIN_ID);

pluginManager.startPlugin(PLUGIN_ID);
pluginManager.getExtensions(PLUGIN_ID);
pluginManager.stopPlugin(PLUGIN_ID);
```

The secons call to `getExtensions` results in an Exception: `java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@4a6facb0 has been closed already`

I figured out the following workaround in [SpringPlugin](/pf4j/pf4j-spring/blob/master/pf4j-spring/src/main/java/org/pf4j/spring/SpringPlugin.java)
```java
    @Override
    public void stop() {
        // close applicationContext
        if ((applicationContext != null) && (applicationContext instanceof ConfigurableApplicationContext)) {
            ((ConfigurableApplicationContext) applicationContext).close();
            **applicationContext = null;**
        }
    }
```

By adding `applicationContext = null` a new application context is created when restarting the plugin. It should work but  I am not 100% sure that there are no side effects so maybe you could have a quick check?

**Comment by decebals** [comment]
@michael-becker Thanks for reporting this issue. 
Can you create a PR please? A PR has a higher visibility (diff, ...). It will be awesome if the PR will contains a unit test.

**Comment by decebals** [comment]
A SNAPSHOT version is available on Maven central repository.
