### ISSUE TITLE
pf4j-spring and Spring Boot

### ISSUE THREAD

**Issue by fhchina** [pf4j/pf4j-spring#8]
I need a demo to use pf4j-spring together with Spring Boot. i.e. integrate pf4j-spring into a spring boot application.

**Comment by fhchina** [comment]
ApplicationContext hierarchy? SpringApplicationBuilder? all help are welcome.

**Comment by laurentkvb** [comment]
Hi, have you tried to make it work?

**Comment by decebals** [comment]
It will be nice if someone share with us a demo project (available on GitHub), something very simple (maybe a fork of the current demo project with Spring Boot).

**Comment by decebals** [comment]
Maybe https://github.com/decebals/pf4j/issues/93#issuecomment-283651852 can help.

**Comment by fhchina** [comment]
I have tried to integrate pf4j-spring with Spring Boot, but I finally found that making Spring Boot works with multi ClassLoader is too difficult. so I just write a simple Plugin Framework, all plugins are shared the current system class loader. By the way, I use Kotlin to write my plugin framework. Java is too ugly to work with it:)

**Comment by laurentkvb** [comment]
I have been looking around and saw the OSGi framework. I have been able to create modules, connect modules together make them work independently from each other. Has anyone got experience in making and OSGi based application, where plug-ins are an important aspect?

**Comment by decebals** [comment]
@fhchina 
> I finally found that making Spring Boot works with multi ClassLoader is too difficult. so I just write a simple Plugin Framework, all plugins are shared the current system class loader.

PF4J can share the same class loader like in your example :smile:.
All you have to do is to override [DefaultPluginLoader#createPluginClassLoader](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/DefaultPluginLoader.java#L57) and to return the same class loader (singleton) for all plugins. I can relax a little bit the signature of method and on return to have a simple Java `ClassLoader` instead of `PluginClassLoader` and so you can return the application class loader.

**Comment by decebals** [comment]
@laurentkvb 
This topic is about PF4J and not about OSGI. I am sure that you will find enough information about OSGI on the internet (Eclipse and majority of Java application server are built using OSGI).

**Comment by decebals** [comment]
I saw that some people succeeded to use PF4J in Spring Boot applications, and from this reason I will close this issue. 
If you thing that the problem is not solved, please open the issue again.

**Comment by reckart** [comment]
@decebals could you provider some pointers to those who have succeeded, in particular if their code is available on GitHub?

**Comment by decebals** [comment]
@reckart 
Sorry for late response. I am busy with PF4J 3.0.

> I saw that some people succeeded to use PF4J in Spring Boot applications, and from this reason I will close this issue.

Maybe it was a good idea to add some details after this affirmation. 
I will add some links that could be useful for people in the context of PF4J and Spring (Boot):
- https://github.com/ralemy/pf4j-spring-tutorial
- https://github.com/vindell/spring-boot-starter-pf4j2
- https://github.com/pf4j/pf4j-spring/issues/15
- https://github.com/pf4j/pf4j-spring/issues/7

I have no experience with Spring Boot. In the past I worked with Spring Framework. I wish to be more active on pf4j-spring project but unfortunately I cannot (I don't have enough knowledge about Spring internal aspects).

**Comment by reckart** [comment]
@decebals thanks :)

**Comment by hank-cp** [comment]
hi everyone, I make a project [sbp](https://github.com/hank-cp/sbp) which is built on top of pf4j to support Spring Boot integration. It should be able to allow you develop a Spring Boot web application in a *PLUGIN* way.

**Comment by gurucube** [comment]
Hi Guys! I see a big opportunity to make synergy here. We need a version for webflux too...
