### ISSUE TITLE
When will plan support Spring6.x ?

### ISSUE THREAD

**Issue by monkeyk** [pf4j/pf4j-spring#80]
We team use pf4j, but use Spring6.x version;
When will plan support Spring6.x ?  which version ?

TKS

**Comment by decebals** [comment]
Have you tested? 
pf4j-spring is a very tiny glue between pf4j and spring, nothing special

**Comment by decebals** [comment]
@monkeyk Please create a new issue.

**Comment by perlun** [comment]
@monkeyk @decebals Please close this issue, since it seems to work as as expected with Spring 6. :slightly_smiling_face:
